import {
  type ProspectProfile,
  type User,
  type ClubHistory,
  UserRole,
  FunnelStage,
  EducationStage,
  EducationSystem,
  EligibilityStatus,
  PriorityLevel,
  PaymentStatus,
} from "@/shared/types";

export const mockUsers: User[] = [
  { id: "u1", email: "admin@n10sport.com", role: UserRole.ADMIN, createdAt: "2024-01-01T00:00:00Z" },
  { id: "u2", email: "sales@n10sport.com", role: UserRole.SALES_REP, createdAt: "2024-02-01T00:00:00Z" },
  { id: "u3", email: "athlete@example.com", role: UserRole.PROSPECT, createdAt: "2024-03-01T00:00:00Z" },
];

export const mockProspects: ProspectProfile[] = [
  {
    id: "p1",
    userId: "u3",
    firstName: "Marcus",
    lastName: "Eriksson",
    dob: "2004-06-15",
    nationality: "Swedish",
    gender: "Male",
    educationStage: EducationStage.SECONDARY,
    educationYearNumber: 3,
    expectedGraduationYear: 2025,
    educationSystem: EducationSystem.EUROPE,
    heightCm: 191,
    weightKg: 82,
    verticalJumpCm: 78,
    sport: "Basketball",
    positions: ["Point Guard", "Shooting Guard"],
    yearsExperience: 8,
    highlightLinks: ["https://youtube.com/watch?v=example1"],
    funnelStage: FunnelStage.HIGHLIGHTS_RECEIVED,
    lastStageUpdate: "2025-01-20T00:00:00Z",
    inactiveFlag: false,
    athleticRating: 4,
    academicRating: 3,
    coachabilityRating: 5,
    priorityLevel: PriorityLevel.HIGH,
    paymentStatus: PaymentStatus.PARTIAL,
    paymentAmount: 2500,
    yearsOfEligibilityRemaining: 4,
    ncaaEligibilityStatus: EligibilityStatus.IN_PROGRESS,
    naiaEligibilityStatus: EligibilityStatus.CLEARED,
    transcriptDriveFileId: "drive_abc123",
    transcriptFileName: "marcus_transcript.pdf",
    transcriptUploadedAt: "2025-01-10T00:00:00Z",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2025-01-20T00:00:00Z",
  },
  {
    id: "p2",
    userId: "u4",
    firstName: "Sofia",
    lastName: "Müller",
    dob: "2005-03-22",
    nationality: "German",
    gender: "Female",
    educationStage: EducationStage.SECONDARY,
    educationYearNumber: 2,
    expectedGraduationYear: 2026,
    educationSystem: EducationSystem.EUROPE,
    heightCm: 175,
    weightKg: 68,
    sport: "Soccer",
    positions: ["Midfielder", "Forward"],
    yearsExperience: 10,
    highlightLinks: [],
    funnelStage: FunnelStage.INITIAL_SUBMISSION,
    lastStageUpdate: "2025-01-28T00:00:00Z",
    inactiveFlag: false,
    paymentStatus: PaymentStatus.NOT_PAID,
    ncaaEligibilityStatus: EligibilityStatus.NOT_STARTED,
    naiaEligibilityStatus: EligibilityStatus.NOT_STARTED,
    createdAt: "2025-01-28T00:00:00Z",
    updatedAt: "2025-01-28T00:00:00Z",
  },
  {
    id: "p3",
    userId: "u5",
    firstName: "Kwame",
    lastName: "Asante",
    dob: "2003-11-08",
    nationality: "Ghanaian",
    gender: "Male",
    educationStage: EducationStage.POST_SECONDARY_UNDERGRADUATE,
    educationYearNumber: 1,
    expectedGraduationYear: 2027,
    educationSystem: EducationSystem.UK,
    heightCm: 198,
    weightKg: 95,
    verticalJumpCm: 85,
    sport: "Basketball",
    positions: ["Center", "Power Forward"],
    yearsExperience: 6,
    highlightLinks: ["https://youtube.com/watch?v=example2", "https://youtube.com/watch?v=example3"],
    funnelStage: FunnelStage.CONTRACT_SIGNED,
    lastStageUpdate: "2024-12-01T00:00:00Z",
    inactiveFlag: true,
    athleticRating: 5,
    academicRating: 3,
    coachabilityRating: 4,
    priorityLevel: PriorityLevel.VIP,
    paymentStatus: PaymentStatus.PAID,
    paymentAmount: 5000,
    paymentDate: "2024-12-15T00:00:00Z",
    yearsOfEligibilityRemaining: 4,
    ncaaEligibilityStatus: EligibilityStatus.CLEARED,
    naiaEligibilityStatus: EligibilityStatus.CLEARED,
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "p4",
    userId: "u6",
    firstName: "Lena",
    lastName: "Johansson",
    dob: "2004-09-12",
    nationality: "Norwegian",
    gender: "Female",
    educationStage: EducationStage.SECONDARY,
    educationYearNumber: 3,
    expectedGraduationYear: 2025,
    educationSystem: EducationSystem.EUROPE,
    heightCm: 180,
    weightKg: 72,
    sport: "Volleyball",
    positions: ["Outside Hitter"],
    yearsExperience: 7,
    highlightLinks: [],
    funnelStage: FunnelStage.FIRST_CALL_COMPLETED,
    lastStageUpdate: "2025-02-01T00:00:00Z",
    inactiveFlag: false,
    paymentStatus: PaymentStatus.NOT_PAID,
    ncaaEligibilityStatus: EligibilityStatus.NOT_STARTED,
    naiaEligibilityStatus: EligibilityStatus.NOT_STARTED,
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-02-01T00:00:00Z",
  },
];

export const mockClubHistory: ClubHistory[] = [
  {
    id: "c1",
    prospectId: "p1",
    clubName: "Djurgårdens IF",
    seasonStartYear: 2020,
    seasonEndYear: 2023,
    leagueLevel: "U19 National",
    achievements: "MVP 2022, League Champions 2021",
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "c2",
    prospectId: "p1",
    clubName: "Stockholm Eagles",
    seasonStartYear: 2018,
    seasonEndYear: 2020,
    leagueLevel: "Youth Regional",
    achievements: "Top Scorer 2019",
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "c3",
    prospectId: "p3",
    clubName: "Accra Lions BC",
    seasonStartYear: 2019,
    seasonEndYear: 2023,
    leagueLevel: "National Premier",
    achievements: "All-Star 2022, National Team Selection",
    createdAt: "2024-06-01T00:00:00Z",
  },
];
